ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "totpSecretEnc" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "totpPendingSecretEnc" TEXT;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "totpEnabledAt" TIMESTAMP(3);
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "backupCodesHash" JSONB;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "totpFailCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Owner" ADD COLUMN IF NOT EXISTS "totpLockedUntil" TIMESTAMP(3);

ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "totpSecretEnc" TEXT;
ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "totpPendingSecretEnc" TEXT;
ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "totpEnabledAt" TIMESTAMP(3);
ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "backupCodesHash" JSONB;
ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "totpFailCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Contributor" ADD COLUMN IF NOT EXISTS "totpLockedUntil" TIMESTAMP(3);

ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpSecretEnc" TEXT;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpPendingSecretEnc" TEXT;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpEnabledAt" TIMESTAMP(3);
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "backupCodesHash" JSONB;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpFailCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Admin" ADD COLUMN IF NOT EXISTS "totpLockedUntil" TIMESTAMP(3);
